### PR TITLE
add support for hot reloading the config.yaml

### PR DESCRIPTION
**Pull request by arnesetzer**
As discussed in #99 a try to enable hot reloading for config (and therefore datasets) without rebuilding the docker image again.

What changed:
A watchdog (`/app/watcher.py`) is etablish via supervisor. On a config.yaml add or change (CAVE: Due to docker limitations it won't happen if the inode changes, see: https://medium.com/@jonsbun/why-need-to-be-careful-when-mounting-single-files-into-a-docker-container-4f929340834) the watchdog is triggerd an kills the uwsgi and flushes memcached.

### CODE REVIEW

**Comment by arnesetzer** [comment]
@ajnisbet Any feedback? 🙈

**Comment by ajnisbet** [comment]
Thanks for this Arne!

It's no my radar! I've been on holiday the last month and there's a few things I'll need to tweak before merging, here's a quick review (for my later reference):

- [ ] Use `subprocess` instead of `os.system`
- [ ] Stop and start `uwsgi` with `supervisord` instead of killing it
- [ ] Add warm cache command
- [ ] Watch both `config.yaml` and `example-config.yaml`

**Comment by arnesetzer** [comment]
Hi, thanks for the feedback. 
>     * [ ]  Use `subprocess` instead of `os.system`
> 
Done, now using pymemcache to avoid any system manipulation.
>     * [ ]  Stop and start `uwsgi` with `supervisord` instead of killing it
> 
I'm a little bit puzzled how to achieve this. I played around with the `supervisorctl` but this requires some serious changes in the supervisord configuration (
>     * [ ]  Add warm cache command
> 
[Already done](https://github.com/arnesetzer/opentopodata/blob/25aec3ea620f04484d5d6cf41ae7e3dc79de0e6a/docker/watcher.py#L21) 😄 
>     * [ ]  Watch both `config.yaml` and `example-config.yaml`
Also done now.

**Comment by ajnisbet** [comment]
Thanks for this work @arnesetzer !

Here's the final working code if you're interested: https://github.com/ajnisbet/opentopodata/commit/d1fc1a733a097b2fbd5dd39336c29a15fb8f0840

**Pull request merged**
